//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mca_coh_gui.Localizations {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization___コピー {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization___コピー() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mca_coh_gui.Localizations.Localization - コピー", typeof(Localization___コピー).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   boot.bin does not exist in the specified directory.
        ///Abort process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BootNotExistText {
            get {
                return ResourceManager.GetString("BootNotExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memory Card Formated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CardFormattedText {
            get {
                return ResourceManager.GetString("CardFormattedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retrieval of the list is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompleteRetrievingText {
            get {
                return ResourceManager.GetString("CompleteRetrievingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoneCaption {
            get {
                return ResourceManager.GetString("DoneCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dump is completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DumpCompletedText {
            get {
                return ResourceManager.GetString("DumpCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image dumped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DumpImageCompletedText {
            get {
                return ResourceManager.GetString("DumpImageCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dumping data from dongle...
        ///Please wait a moment. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DumpingDataText {
            get {
                return ResourceManager.GetString("DumpingDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dumping image: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DumpingImageText {
            get {
                return ResourceManager.GetString("DumpingImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dumping image to the dongle...
        ///Please wait a moment. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DumpingImgText {
            get {
                return ResourceManager.GetString("DumpingImgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dumping: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DumpingText {
            get {
                return ResourceManager.GetString("DumpingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorOccuredText {
            get {
                return ResourceManager.GetString("ErrorOccuredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to connect or attach the memory card adapter.
        ///Please check if the adapter is connected or the driver is installed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedAttachText {
            get {
                return ResourceManager.GetString("FailedAttachText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key file dump failed.
        ///Abort process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedKeyDumpText {
            get {
                return ResourceManager.GetString("FailedKeyDumpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   boot.bin data: {0}
        ///key data: {1}
        ///Key validation failed.
        ///Abort operation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedKeyVerifyText {
            get {
                return ResourceManager.GetString("FailedKeyVerifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to retrieve the list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedRetrievingText {
            get {
                return ResourceManager.GetString("FailedRetrievingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_AllFiles {
            get {
                return ResourceManager.GetString("Filter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   boot.bin|boot.bin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_boot {
            get {
                return ResourceManager.GetString("Filter_boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image (*.img)|*.img に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_Image {
            get {
                return ResourceManager.GetString("Filter_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key file (*.hex,*.key,*.bin)|*.hex;*.key;*.bin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_Key {
            get {
                return ResourceManager.GetString("Filter_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dongle formatting is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatCompletedText {
            get {
                return ResourceManager.GetString("FormatCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trying to format dongle. If I do, all data in the dongle will be lost.
        ///This operation cannot be undone.
        ///Do you want to perform the formatting? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatConfirmText {
            get {
                return ResourceManager.GetString("FormatConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Formatted memory card.
        ///Please wait a moment and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormattedText {
            get {
                return ResourceManager.GetString("FormattedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Formatting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormattingText {
            get {
                return ResourceManager.GetString("FormattingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0}
        ///Name: {1}
        ///Maker: {2}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetInfoText {
            get {
                return ResourceManager.GetString("GetInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InformationCaption {
            get {
                return ResourceManager.GetString("InformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitializingText {
            get {
                return ResourceManager.GetString("InitializingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key dump is completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyDumpCompletedText {
            get {
                return ResourceManager.GetString("KeyDumpCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key dump is successfully.
        ///Dumped key data: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyDumpSuccessText {
            get {
                return ResourceManager.GetString("KeyDumpSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   boot.bin data: {0}
        ///key data: {1}
        ///Key verification succeeded.
        ///Continue to write the file to the dongle. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyVerifyedText {
            get {
                return ResourceManager.GetString("KeyVerifyedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There was no response from mca-coh. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoresponseText {
            get {
                return ResourceManager.GetString("NoresponseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sys2x6 dongle card not inserted or not recognized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotInsertText {
            get {
                return ResourceManager.GetString("NotInsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dongle information could not be obtained. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ObtainedDongleInformationText {
            get {
                return ResourceManager.GetString("ObtainedDongleInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessingText {
            get {
                return ResourceManager.GetString("ProcessingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing type unknown. Closes dialog after a few seconds. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessUnknownText {
            get {
                return ResourceManager.GetString("ProcessUnknownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} / {1} Files completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressText {
            get {
                return ResourceManager.GetString("ProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove is completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveCompletedText {
            get {
                return ResourceManager.GetString("RemoveCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove &apos;{0}&apos; from dongle. Do you wish to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveConfirmText {
            get {
                return ResourceManager.GetString("RemoveConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove data to the dongle...
        ///Please wait a moment. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemovingDataText {
            get {
                return ResourceManager.GetString("RemovingDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removing: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemovingText {
            get {
                return ResourceManager.GetString("RemovingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retrieving the list... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RetrievingText {
            get {
                return ResourceManager.GetString("RetrievingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify where to save the dump file(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecifyDumpFileCaption {
            get {
                return ResourceManager.GetString("SpecifyDumpFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify where to write the file(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecifyWriteFileCaption {
            get {
                return ResourceManager.GetString("SpecifyWriteFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to recognize dongle.
        ///PS2 memory card (SCPH-10020) cannot be read.
        ///Only Sys2x6 dongle (COH-H10020) can be read. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnableRecognizeText {
            get {
                return ResourceManager.GetString("UnableRecognizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningCaption {
            get {
                return ResourceManager.GetString("WarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Never unplug the dongle or unplug the memory card adapter while writing.
        ///The dongle may be damaged.&apos;&apos; Select &apos;Yes&apos; to start writing to the Sys2x6 dongle. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningUnplugText {
            get {
                return ResourceManager.GetString("WarningUnplugText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The boot.bin key has been rewritten. Do you want to write boot.bin after dongle rewriting? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WritebootConfirmText {
            get {
                return ResourceManager.GetString("WritebootConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write is completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WriteCompleteText {
            get {
                return ResourceManager.GetString("WriteCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writes data to the dongle for Sys2x6.
        ///If the correct file is not written, the game will not be loaded. Do you wish to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WriteDataConfirmText {
            get {
                return ResourceManager.GetString("WriteDataConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key writed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WritedKeyText {
            get {
                return ResourceManager.GetString("WritedKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key write is completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WriteKeyCompletedText {
            get {
                return ResourceManager.GetString("WriteKeyCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writing data to the dongle...
        ///Please wait a moment. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WritingDataText {
            get {
                return ResourceManager.GetString("WritingDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writing: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WritingText {
            get {
                return ResourceManager.GetString("WritingText", resourceCulture);
            }
        }
    }
}
